spring:
  profiles:
    active:
    - dev
--- 
spring: 
  profiles: dev
  application:
    name: xy-spring-cloud-config-server #eurakla中对外暴露的微服务名字， 与server.context-path有什么区别

--- 
spring: 
  profiles:
    active: test
  application:
    name: xy-spring-cloud-config-server #eurakla中对外暴露的微服务名字， 与server.context-path有什么区别