spring:
  profiles:
    active:
    - dev
--- 
spring: 
  profiles: dev
  application:
    name: xy-spring-cloud-config-server

--- 
spring: 
  profiles:
    active: test
  application:
    name: xy-spring-cloud-config-server
