spring:
  profiles:
    active:
    - dev
--- 
spring: 
  profiles: dev
  application:
    name: xy-spring-cloud-config-server-dev #eurakla中对外暴露的微服务名字， 与server.context-path有什么区别
--- 
spring: 
  profiles: test
  application:
    name: xy-spring-cloud-config-server-test #eurakla中对外暴露的微服务名字， 与server.context-path有什么区别
---
spring: 
  profiles: pro
  application:
    name: xy-spring-cloud-config-server-pro #eurakla中对外暴露的微服务名字， 与server.context-path有什么区别